name: Deployment
on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Testing on deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_mysql
          tools: composer:v2

      - name: Setup Env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install

      - name: Generate key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

  deploy:
    name: Deploying to production
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: SSH into Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ vars.PROJECT_PATH }}
            git pull origin develop
            composer install --no-dev --optimize-autoloader
            php artisan optimize:clear
            php artisan migrate --force
            php artisan optimize
            echo "Deployment completed successfully"
